<a href="https://colab.research.google.com/github/omeesha1234567/Machine-learning-Lab/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment-1

Explore ML tools such as Python (scikit-learn), WEKA, and Orange. Load
and visualize structured datasets like Titanic. Generate statistical
summaries and plots. Apply appropriate data preprocessing.

In [ ]:
import pandas as pd

df = pd.read_csv('Titanic-Dataset.csv')
display(df.head())
df.shape
df.info

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [ ]:
import numpy as np

# Create age groups
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80]
labels = ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80']
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)

display(df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,21-30
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,31-40
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,21-30
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,31-40
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,31-40

In [ ]:
survival_rate_by_age = df.groupby('AgeGroup', observed=False)['Survived'].value_counts(normalize=True).unstack()
survival_rate_by_age['SurvivalRate'] = survival_rate_by_age[1] # Survival rate is the proportion of survived (1)
display(survival_rate_by_age[['SurvivalRate']])

/tmp/ipython-input-1924117613.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survival_rate_by_age = df.groupby('AgeGroup')['Survived'].value_counts(normalize=True).unstack()

Survived  SurvivalRate
AgeGroup
0-10          0.612903
11-20         0.401961
21-30         0.350000
31-40         0.437126
41-50         0.382022
51-60         0.416667
61-70         0.315789
71-80         0.000000

LAB -2 IPL DATA SET

In [8]:
import pandas as pd

df = pd.read_csv('ipl_dataset.csv')

print("Column names:")
print(ipl_df.columns.tolist())

print("\nData types:")
print(ipl_df.info())
print("head 5 transpose")
df.head(5).transpose()
print("shape")
df.shape
df.COUNTRY.value_counts()

Column names:
['Sl.NO.', 'PLAYER NAME', 'AGE', 'COUNTRY', 'TEAM', 'PLAYING ROLE', 'T-RUNS', 'T-WKTS', 'ODI-RUNS-S', 'ODI-SR-B', 'ODI-WKTS', 'ODI-SR-BL', 'CAPTAINCY EXP', 'RUNS-S', 'HS', 'AVE', 'SR-B', 'SIXERS', 'RUNS-C', 'WKTS', 'AVE-BL', 'ECON', 'SR-BL', 'AUCTION YEAR', 'BASE PRICE', 'SOLD PRICE']

Data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl.NO.         130 non-null    int64
 1   PLAYER NAME    130 non-null    object
 2   AGE            130 non-null    int64
 3   COUNTRY        130 non-null    object
 4   TEAM           130 non-null    object
 5   PLAYING ROLE   130 non-null    object
 6   T-RUNS         130 non-null    int64
 7   T-WKTS         130 non-null    int64
 8   ODI-RUNS-S     130 non-null    int64
 9   ODI-SR-B       130 non-null    float64
 10  ODI-WKTS       130 non-null    int64
 11  ODI-SR-BL      130 non-null    float64
 12  CAPTAINCY EXP  130 non-null    int64
 13  RUNS-S         130 non-null    int64
 14  HS             130 non-null    int64
 15  AVE            130 non-null    float64
 16  SR-B           130 non-null    float64
 17  SIXERS         130 non-null    int64
 18  RUNS-C         130 non-null    int64
 19  WKTS           130 non-null    int64
 20  AVE-BL         130 non-null    float64
 21  ECON           130 non-null    float64
 22  SR-BL          130 non-null    float64
 23  AUCTION YEAR   130 non-null    int64
 24  BASE PRICE     130 non-null    int64
 25  SOLD PRICE     130 non-null    int64
dtypes: float64(7), int64(15), object(4)
memory usage: 26.5+ KB
None
head 5 transpose
shape

COUNTRY
IND    53
AUS    22
SA     16
SL     12
PAK     9
NZ      7
WI      6
ENG     3
BAN     1
ZIM     1
Name: count, dtype: int64